---
title: "Research"
---

## Peer-Reviewed Publications

Scarrow, Susan E., **JeongKyu Suh**, and Jamie M. Wright. 2025. ["Explaining the Narrowing Gender Gap in Partisan Participation: Women's Empowerment or Men's Disengagement?"](https://doi.org/10.1177/00323217241297628) *Political Studies* 73(4): 1461-1483.

Clifford, Scott, Elizabeth Simas, and **JeongKyu Suh**. 2025. ["The Policy Basis of Group Sentiments."](https://doi.org/10.1017/psrm.2024.30) *Political Science Research and Methods* 13(2): 482-488.

**Suh, JeongKyu**. 2017. ["How National Identity Shapes South Koreans' Attitudes toward North Korea and Its Defectors."](https://doi.org/10.18848/2327-0071/CGP/v12i01/13-42) *The International Journal of Interdisciplinary Civic and Political Studies* 12(1): 13-42.


## Selected Works in Progress

**Dissertation: *Whose Side Are They On? Party-Race Linkage Stereotypes and the Partisanization of Racial and Immigration Attitudes***

"When Partisan Affect Spills Over: The Conditional Spillover of Affective Polarization into Racial Group Evaluation" *(In preparation for submission; draft available upon request)*


**Other Projects**

"Political Psychology and Intraparty Politics: The Dispositional Foundations of Factionalism in U.S. Primaries" (with Trent Ollerenshaw and Lucas Lothamer)

“Anti-Trans Spillover or Anti-Woke Backlash? Explaining the Reversal of Support for Gay Rights among Republicans" (with Trent Ollerenshaw and POLS 6365 UH graduate students)

"Perceived Threats from Immigrants' Political Participation and the Limited Impact of Ethnocentrism: Evidence from a Survey Experiment in South Korea" (with Shang E. Ha)

"Do Colors Function as Political Stereotypes? The Hidden Priming Effect of Color in Candidate Evaluations"

*See my [CV](cv.qmd) for additional works in progress.*


## Other Publications: DataSets & Programming

Kang, TaeYoung, Eunrang Kwon, Junbum Lee, Youngeun Nam, Junmo Song, and **JeongKyu Suh**. 2022. ["Korean Online Hate Speech Dataset for Multilabel Classification: How Can Social Science Improve Dataset on Hate Speech?"](https://doi.org/10.48550/arXiv.2204.03262) arXiv preprint arXiv:2204.03262 [[dataset link]](https://github.com/sgunderscore/hatescore-korean-hate-speech)


## Peer-Reviewed Publications in Korean

Jang, Seung-Jin and **JeongKyu Suh**. 2019. ["Dual Structures of Partisan Polarization in the Korean Electorate: Political Identity, Issue Preferences, and Political Sophistication."](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002508283) *Korean Party Studies Review* 18(3): 5-29.

**Suh, JeongKyu** and Shang E. Ha. 2019. ["Socialization and Political Participation of Immigrants in South Korea."](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002482539) *Korean Political Science Review* 53(2): 81-103.

**Suh, JeongKyu** and Hyeon-Woo Lee. 2017. ["Congressmen's Strategic Voting Behavior Across Time: How Many Days Are Left to the Next Election?"](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002270635) *The 21st Century Political Science Review* 27(3): 27-50.
